### ISSUE TITLE
Merge data entry enpoints

### ISSUE THREAD

**Issue by MartinDelille** [PoissonPilote/status-api#3]
It'll be cool if all data would be optionnal. Sometime we want to post info but the GPS is unavailable for any reason.

**Comment by divarvel** [comment]
On the boat, the GPS point is the only useful information (the depth is 0 for boats, the rest is generated).
So I don't see the point

**Comment by divarvel** [comment]
Ok, so

```
POST /api/data

[<data_point>]
```

where data_points is either

```
{x, y, [depth], [datetime]}
```

or

```
{type: "type", value: <value>, [datetime]}
```

**Comment by MartinDelille** [comment]
Would it work?

```
[
   {x=3, y=5},
   {type=paddle, value=34253, date=01/03/2016 4h32}
]
```

**Comment by divarvel** [comment]
yes (provided you use iso8601 for the datetime field)

**Comment by divarvel** [comment]
https://github.com/PoissonPilote/status-api/commit/94d27ac006a605dbbd9164e401cd133edc15c8db
